// DO NOT MODIFY.  This file is automatically generated by `constants.py`
// in the rex-font repo.
//
// Font: TODO
// Modified: 2017-08-06 17:34:11

use font_types::FontUnit;

pub const NULL_DELIMITER_SPACE: FontUnit = fontunit!(100);
pub const DELIMITER_SHORT_FALL: FontUnit = fontunit!(100);
pub const DELIMITER_FACTOR: FontUnit = fontunit_raw!(0xE6); // 90.1%

pub const UNITS_PER_EM: FontUnit = fontunit!(1000);
pub const MIN_CONNECTOR_OVERLAP: FontUnit = fontunit!(100);

pub const ACCENT_BASE_HEIGHT: FontUnit = fontunit!(480);
pub const AXIS_HEIGHT: FontUnit = fontunit!(258);
pub const DELIMITED_SUB_FORMULA_MIN_HEIGHT: FontUnit = fontunit!(1325);
pub const DISPLAY_OPERATOR_MIN_HEIGHT: FontUnit = fontunit!(1800);
pub const FLATTENED_ACCENT_BASE_HEIGHT: FontUnit = fontunit!(656);
pub const FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(150);
pub const FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN: FontUnit = fontunit!(640);
pub const FRACTION_DENOMINATOR_GAP_MIN: FontUnit = fontunit!(68);
pub const FRACTION_DENOMINATOR_SHIFT_DOWN: FontUnit = fontunit!(585);
pub const FRACTION_NUM_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(150);
pub const FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP: FontUnit = fontunit!(640);
pub const FRACTION_NUMERATOR_GAP_MIN: FontUnit = fontunit!(68);
pub const FRACTION_NUMERATOR_SHIFT_UP: FontUnit = fontunit!(585);
pub const FRACTION_RULE_THICKNESS: FontUnit = fontunit!(68);
pub const LOWER_LIMIT_BASELINE_DROP_MIN: FontUnit = fontunit!(670);
pub const LOWER_LIMIT_GAP_MIN: FontUnit = fontunit!(135);
pub const MATH_LEADING: FontUnit = fontunit!(150);
pub const OVERBAR_EXTRA_ASCENDER: FontUnit = fontunit!(68);
pub const OVERBAR_RULE_THICKNESS: FontUnit = fontunit!(68);
pub const OVERBAR_VERTICAL_GAP: FontUnit = fontunit!(175);
pub const RADICAL_DEGREE_BOTTOM_RAISE_PERCENT: FontUnit = fontunit!(55);
pub const RADICAL_DISPLAY_STYLE_VERTICAL_GAP: FontUnit = fontunit!(170);
pub const RADICAL_EXTRA_ASCENDER: FontUnit = fontunit!(68);
pub const RADICAL_KERN_AFTER_DEGREE: FontUnit = fontunit!(-335);
pub const RADICAL_KERN_BEFORE_DEGREE: FontUnit = fontunit!(65);
pub const RADICAL_RULE_THICKNESS: FontUnit = fontunit!(68);
pub const RADICAL_VERTICAL_GAP: FontUnit = fontunit!(85);
pub const SKEWED_FRACTION_HORIZONTAL_GAP: FontUnit = fontunit!(350);
pub const SKEWED_FRACTION_VERTICAL_GAP: FontUnit = fontunit!(68);
pub const SPACE_AFTER_SCRIPT: FontUnit = fontunit!(40);
pub const STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN: FontUnit = fontunit!(690);
pub const STACK_BOTTOM_SHIFT_DOWN: FontUnit = fontunit!(385);
pub const STACK_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(300);
pub const STACK_GAP_MIN: FontUnit = fontunit!(150);
pub const STACK_TOP_DISPLAY_STYLE_SHIFT_UP: FontUnit = fontunit!(780);
pub const STACK_TOP_SHIFT_UP: FontUnit = fontunit!(470);
pub const STRETCH_STACK_BOTTOM_SHIFT_DOWN: FontUnit = fontunit!(590);
pub const STRETCH_STACK_GAP_ABOVE_MIN: FontUnit = fontunit!(68);
pub const STRETCH_STACK_GAP_BELOW_MIN: FontUnit = fontunit!(68);
pub const STRETCH_STACK_TOP_SHIFT_UP: FontUnit = fontunit!(800);
pub const SUB_SUPERSCRIPT_GAP_MIN: FontUnit = fontunit!(150);
pub const SUBSCRIPT_BASELINE_DROP_MIN: FontUnit = fontunit!(160);
pub const SUBSCRIPT_SHIFT_DOWN: FontUnit = fontunit!(210);
pub const SUBSCRIPT_TOP_MAX: FontUnit = fontunit!(368);
pub const SUPERSCRIPT_BASELINE_DROP_MAX: FontUnit = fontunit!(230);
pub const SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT: FontUnit = fontunit!(380);
pub const SUPERSCRIPT_BOTTOM_MIN: FontUnit = fontunit!(120);
pub const SUPERSCRIPT_SHIFT_UP: FontUnit = fontunit!(360);
pub const SUPERSCRIPT_SHIFT_UP_CRAMPED: FontUnit = fontunit!(252);
pub const UNDERBAR_EXTRA_DESCENDER: FontUnit = fontunit!(68);
pub const UNDERBAR_RULE_THICKNESS: FontUnit = fontunit!(68);
pub const UNDERBAR_VERTICAL_GAP: FontUnit = fontunit!(175);
pub const UPPER_LIMIT_BASELINE_RISE_MIN: FontUnit = fontunit!(300);
pub const UPPER_LIMIT_GAP_MIN: FontUnit = fontunit!(135);

pub const SCRIPT_PERCENT_SCALE_DOWN: FontUnit = fontunit_raw!(0xb3); // 70 %
pub const SCRIPT_SCRIPT_PERCENT_SCALE_DOWN: FontUnit = fontunit_raw!(0x8c); // 55 %
