// DO NOT MODIFY.  This file is automatically generated by ___ in the rex-font folder.
//
// Font File: master/xits.otf
// Font Nmae: b'XITS Math'
#![allow(dead_code)]
use dimensions::FontUnit;
use dimensions::Pixels;

pub static UNITS_PER_EM                                   : FontUnit<f64> = FontUnit(1000.0);
pub static MIN_CONNECTOR_OVERLAP                          : FontUnit<u32> = FontUnit(50);

pub static NULL_DELIMITER_SPACE                          : Pixels        = Pixels(1.6);  // This should probably depend on font size.
pub static DELIMITER_SHORT_FALL                          : FontUnit<u16> = FontUnit(100);
pub static DELIMITER_FACTOR                              : f64           = 901.0/1000.0;

pub static ACCENT_BASE_HEIGHT                             : FontUnit<f64> = FontUnit(450.0);
pub static AXIS_HEIGHT                                    : FontUnit<f64> = FontUnit(250.0);
pub static DELIMITED_SUB_FORMULA_MIN_HEIGHT               : FontUnit<f64> = FontUnit(1500.0);
pub static DISPLAY_OPERATOR_MIN_HEIGHT                    : FontUnit<f64> = FontUnit(1450.0);
pub static FLATTENED_ACCENT_BASE_HEIGHT                   : FontUnit<f64> = FontUnit(662.0);
pub static FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN           : FontUnit<f64> = FontUnit(198.0);
pub static FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN  : FontUnit<f64> = FontUnit(700.0);
pub static FRACTION_DENOMINATOR_GAP_MIN                   : FontUnit<f64> = FontUnit(66.0);
pub static FRACTION_DENOMINATOR_SHIFT_DOWN                : FontUnit<f64> = FontUnit(480.0);
pub static FRACTION_NUM_DISPLAY_STYLE_GAP_MIN             : FontUnit<f64> = FontUnit(198.0);
pub static FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP      : FontUnit<f64> = FontUnit(580.0);
pub static FRACTION_NUMERATOR_GAP_MIN                     : FontUnit<f64> = FontUnit(66.0);
pub static FRACTION_NUMERATOR_SHIFT_UP                    : FontUnit<f64> = FontUnit(480.0);
pub static FRACTION_RULE_THICKNESS                        : FontUnit<f64> = FontUnit(66.0);
pub static LOWER_LIMIT_BASELINE_DROP_MIN                  : FontUnit<f64> = FontUnit(600.0);
pub static LOWER_LIMIT_GAP_MIN                            : FontUnit<f64> = FontUnit(150.0);
pub static MATH_LEADING                                   : FontUnit<f64> = FontUnit(150.0);
pub static OVERBAR_EXTRA_ASCENDER                         : FontUnit<f64> = FontUnit(66.0);
pub static OVERBAR_RULE_THICKNESS                         : FontUnit<f64> = FontUnit(66.0);
pub static OVERBAR_VERTICAL_GAP                           : FontUnit<f64> = FontUnit(198.0);
pub static RADICAL_DEGREE_BOTTOM_RAISE_PERCENT            : FontUnit<f64> = FontUnit(70.0);
pub static RADICAL_DISPLAY_STYLE_VERTICAL_GAP             : FontUnit<f64> = FontUnit(186.0);
pub static RADICAL_EXTRA_ASCENDER                         : FontUnit<f64> = FontUnit(66.0);
pub static RADICAL_KERN_AFTER_DEGREE                      : FontUnit<f64> = FontUnit(-555.0);
pub static RADICAL_KERN_BEFORE_DEGREE                     : FontUnit<f64> = FontUnit(277.0);
pub static RADICAL_RULE_THICKNESS                         : FontUnit<f64> = FontUnit(66.0);
pub static RADICAL_VERTICAL_GAP                           : FontUnit<f64> = FontUnit(82.0);
pub static SCRIPT_PERCENT_SCALE_DOWN                      : FontUnit<f64> = FontUnit(75.0);
pub static SCRIPT_SCRIPT_PERCENT_SCALE_DOWN               : FontUnit<f64> = FontUnit(60.0);
pub static SKEWED_FRACTION_HORIZONTAL_GAP                 : FontUnit<f64> = FontUnit(300.0);
pub static SKEWED_FRACTION_VERTICAL_GAP                   : FontUnit<f64> = FontUnit(66.0);
pub static SPACE_AFTER_SCRIPT                             : FontUnit<f64> = FontUnit(41.0);
pub static STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN          : FontUnit<f64> = FontUnit(900.0);
pub static STACK_BOTTOM_SHIFT_DOWN                        : FontUnit<f64> = FontUnit(800.0);
pub static STACK_DISPLAY_STYLE_GAP_MIN                    : FontUnit<f64> = FontUnit(462.0);
pub static STACK_GAP_MIN                                  : FontUnit<f64> = FontUnit(198.0);
pub static STACK_TOP_DISPLAY_STYLE_SHIFT_UP               : FontUnit<f64> = FontUnit(580.0);
pub static STACK_TOP_SHIFT_UP                             : FontUnit<f64> = FontUnit(480.0);
pub static STRETCH_STACK_BOTTOM_SHIFT_DOWN                : FontUnit<f64> = FontUnit(600.0);
pub static STRETCH_STACK_GAP_ABOVE_MIN                    : FontUnit<f64> = FontUnit(150.0);
pub static STRETCH_STACK_GAP_BELOW_MIN                    : FontUnit<f64> = FontUnit(150.0);
pub static STRETCH_STACK_TOP_SHIFT_UP                     : FontUnit<f64> = FontUnit(300.0);
pub static SUB_SUPERSCRIPT_GAP_MIN                        : FontUnit<f64> = FontUnit(264.0);
pub static SUBSCRIPT_BASELINE_DROP_MIN                    : FontUnit<f64> = FontUnit(50.0);
pub static SUBSCRIPT_SHIFT_DOWN                           : FontUnit<f64> = FontUnit(250.0);
pub static SUBSCRIPT_TOP_MAX                              : FontUnit<f64> = FontUnit(400.0);
pub static SUPERSCRIPT_BASELINE_DROP_MAX                  : FontUnit<f64> = FontUnit(375.0);
pub static SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT          : FontUnit<f64> = FontUnit(400.0);
pub static SUPERSCRIPT_BOTTOM_MIN                         : FontUnit<f64> = FontUnit(125.0);
pub static SUPERSCRIPT_SHIFT_UP                           : FontUnit<f64> = FontUnit(400.0);
pub static SUPERSCRIPT_SHIFT_UP_CRAMPED                   : FontUnit<f64> = FontUnit(275.0);
pub static UNDERBAR_EXTRA_DESCENDER                       : FontUnit<f64> = FontUnit(66.0);
pub static UNDERBAR_RULE_THICKNESS                        : FontUnit<f64> = FontUnit(66.0);
pub static UNDERBAR_VERTICAL_GAP                          : FontUnit<f64> = FontUnit(198.0);
pub static UPPER_LIMIT_BASELINE_RISE_MIN                  : FontUnit<f64> = FontUnit(300.0);
pub static UPPER_LIMIT_GAP_MIN                            : FontUnit<f64> = FontUnit(150.0);