// DO NOT MODIFY.  This file is automatically generated by ___ in the rex-font folder.
//
// Font File: .\master\xits.otf
// Font Nmae: b'XITS Math'
#![allow(dead_code)]
use dimensions::FontUnit;

pub static MIN_CONNECTOR_OVERLAP: FontUnit<u16> = FontUnit(50);
pub static UNITS_PER_EM: FontUnit<u16> = FontUnit(1000);

pub static ACCENT_BASE_HEIGHT                            : FontUnit<i16> = FontUnit(450);
pub static AXIS_HEIGHT                                   : FontUnit<i16> = FontUnit(250);
pub static DELIMITED_SUB_FORMULA_MIN_HEIGHT              : FontUnit<i16> = FontUnit(1500);
pub static DISPLAY_OPERATOR_MIN_HEIGHT                   : FontUnit<i16> = FontUnit(1450);
pub static FLATTENED_ACCENT_BASE_HEIGHT                  : FontUnit<i16> = FontUnit(662);
pub static FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN          : FontUnit<i16> = FontUnit(198);
pub static FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN : FontUnit<i16> = FontUnit(700);
pub static FRACTION_DENOMINATOR_GAP_MIN                  : FontUnit<i16> = FontUnit(66);
pub static FRACTION_DENOMINATOR_SHIFT_DOWN               : FontUnit<i16> = FontUnit(480);
pub static FRACTION_NUM_DISPLAY_STYLE_GAP_MIN            : FontUnit<i16> = FontUnit(198);
pub static FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP     : FontUnit<i16> = FontUnit(580);
pub static FRACTION_NUMERATOR_GAP_MIN                    : FontUnit<i16> = FontUnit(66);
pub static FRACTION_NUMERATOR_SHIFT_UP                   : FontUnit<i16> = FontUnit(480);
pub static FRACTION_RULE_THICKNESS                       : FontUnit<i16> = FontUnit(66);
pub static LOWER_LIMIT_BASELINE_DROP_MIN                 : FontUnit<i16> = FontUnit(600);
pub static LOWER_LIMIT_GAP_MIN                           : FontUnit<i16> = FontUnit(150);
pub static MATH_LEADING                                  : FontUnit<i16> = FontUnit(150);
pub static OVERBAR_EXTRA_ASCENDER                        : FontUnit<i16> = FontUnit(66);
pub static OVERBAR_RULE_THICKNESS                        : FontUnit<i16> = FontUnit(66);
pub static OVERBAR_VERTICAL_GAP                          : FontUnit<i16> = FontUnit(198);
pub static RADICAL_DEGREE_BOTTOM_RAISE_PERCENT           : FontUnit<i16> = FontUnit(70);
pub static RADICAL_DISPLAY_STYLE_VERTICAL_GAP            : FontUnit<i16> = FontUnit(186);
pub static RADICAL_EXTRA_ASCENDER                        : FontUnit<i16> = FontUnit(66);
pub static RADICAL_KERN_AFTER_DEGREE                     : FontUnit<i16> = FontUnit(-555);
pub static RADICAL_KERN_BEFORE_DEGREE                    : FontUnit<i16> = FontUnit(277);
pub static RADICAL_RULE_THICKNESS                        : FontUnit<i16> = FontUnit(66);
pub static RADICAL_VERTICAL_GAP                          : FontUnit<i16> = FontUnit(82);
pub static SCRIPT_PERCENT_SCALE_DOWN                     : FontUnit<i16> = FontUnit(75);
pub static SCRIPT_SCRIPT_PERCENT_SCALE_DOWN              : FontUnit<i16> = FontUnit(60);
pub static SKEWED_FRACTION_HORIZONTAL_GAP                : FontUnit<i16> = FontUnit(300);
pub static SKEWED_FRACTION_VERTICAL_GAP                  : FontUnit<i16> = FontUnit(66);
pub static SPACE_AFTER_SCRIPT                            : FontUnit<i16> = FontUnit(41);
pub static STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN         : FontUnit<i16> = FontUnit(900);
pub static STACK_BOTTOM_SHIFT_DOWN                       : FontUnit<i16> = FontUnit(800);
pub static STACK_DISPLAY_STYLE_GAP_MIN                   : FontUnit<i16> = FontUnit(462);
pub static STACK_GAP_MIN                                 : FontUnit<i16> = FontUnit(198);
pub static STACK_TOP_DISPLAY_STYLE_SHIFT_UP              : FontUnit<i16> = FontUnit(580);
pub static STACK_TOP_SHIFT_UP                            : FontUnit<i16> = FontUnit(480);
pub static STRETCH_STACK_BOTTOM_SHIFT_DOWN               : FontUnit<i16> = FontUnit(600);
pub static STRETCH_STACK_GAP_ABOVE_MIN                   : FontUnit<i16> = FontUnit(150);
pub static STRETCH_STACK_GAP_BELOW_MIN                   : FontUnit<i16> = FontUnit(150);
pub static STRETCH_STACK_TOP_SHIFT_UP                    : FontUnit<i16> = FontUnit(300);
pub static SUB_SUPERSCRIPT_GAP_MIN                       : FontUnit<i16> = FontUnit(264);
pub static SUBSCRIPT_BASELINE_DROP_MIN                   : FontUnit<i16> = FontUnit(50);
pub static SUBSCRIPT_SHIFT_DOWN                          : FontUnit<i16> = FontUnit(250);
pub static SUBSCRIPT_TOP_MAX                             : FontUnit<i16> = FontUnit(400);
pub static SUPERSCRIPT_BASELINE_DROP_MAX                 : FontUnit<i16> = FontUnit(375);
pub static SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT         : FontUnit<i16> = FontUnit(400);
pub static SUPERSCRIPT_BOTTOM_MIN                        : FontUnit<i16> = FontUnit(125);
pub static SUPERSCRIPT_SHIFT_UP                          : FontUnit<i16> = FontUnit(400);
pub static SUPERSCRIPT_SHIFT_UP_CRAMPED                  : FontUnit<i16> = FontUnit(275);
pub static UNDERBAR_EXTRA_DESCENDER                      : FontUnit<i16> = FontUnit(66);
pub static UNDERBAR_RULE_THICKNESS                       : FontUnit<i16> = FontUnit(66);
pub static UNDERBAR_VERTICAL_GAP                         : FontUnit<i16> = FontUnit(198);
pub static UPPER_LIMIT_BASELINE_RISE_MIN                 : FontUnit<i16> = FontUnit(300);
pub static UPPER_LIMIT_GAP_MIN                           : FontUnit<i16> = FontUnit(150);