// DO NOT MODIFY.  This file is automatically generated by ___ in the rex-font folder.
//
// Font File: master/xits.otf
// Font Nmae: b'XITS Math'
#![allow(dead_code)]
use dimensions::FontUnit;
use dimensions::FixedPoint;

pub static UNITS_PER_EM                                   : FontUnit = fontunit!(1000);
pub static MIN_CONNECTOR_OVERLAP                          : FontUnit = fontunit!(50);
pub static NULL_DELIMITER_SPACE                           : FontUnit = fontunit!(100);
pub static DELIMITER_SHORT_FALL                           : FontUnit = fontunit!(100);
pub static DELIMITER_FACTOR                               : FontUnit = fontunit_raw!(0xE6); // 90.1%
pub static ACCENT_BASE_HEIGHT                             : FontUnit = fontunit!(450);
pub static AXIS_HEIGHT                                    : FontUnit = fontunit!(250);
pub static DELIMITED_SUB_FORMULA_MIN_HEIGHT               : FontUnit = fontunit!(1500);
pub static DISPLAY_OPERATOR_MIN_HEIGHT                    : FontUnit = fontunit!(1450);
pub static FLATTENED_ACCENT_BASE_HEIGHT                   : FontUnit = fontunit!(662);
pub static FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN           : FontUnit = fontunit!(198);
pub static FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN  : FontUnit = fontunit!(700);
pub static FRACTION_DENOMINATOR_GAP_MIN                   : FontUnit = fontunit!(66);
pub static FRACTION_DENOMINATOR_SHIFT_DOWN                : FontUnit = fontunit!(480);
pub static FRACTION_NUM_DISPLAY_STYLE_GAP_MIN             : FontUnit = fontunit!(198);
pub static FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP      : FontUnit = fontunit!(580);
pub static FRACTION_NUMERATOR_GAP_MIN                     : FontUnit = fontunit!(66);
pub static FRACTION_NUMERATOR_SHIFT_UP                    : FontUnit = fontunit!(480);
pub static FRACTION_RULE_THICKNESS                        : FontUnit = fontunit!(66);
pub static LOWER_LIMIT_BASELINE_DROP_MIN                  : FontUnit = fontunit!(600);
pub static LOWER_LIMIT_GAP_MIN                            : FontUnit = fontunit!(150);
pub static MATH_LEADING                                   : FontUnit = fontunit!(150);
pub static OVERBAR_EXTRA_ASCENDER                         : FontUnit = fontunit!(66);
pub static OVERBAR_RULE_THICKNESS                         : FontUnit = fontunit!(66);
pub static OVERBAR_VERTICAL_GAP                           : FontUnit = fontunit!(198);
pub static RADICAL_DEGREE_BOTTOM_RAISE_PERCENT            : FontUnit = fontunit!(70);
pub static RADICAL_DISPLAY_STYLE_VERTICAL_GAP             : FontUnit = fontunit!(186);
pub static RADICAL_EXTRA_ASCENDER                         : FontUnit = fontunit!(66);
pub static RADICAL_KERN_AFTER_DEGREE                      : FontUnit = fontunit!(-550);
pub static RADICAL_KERN_BEFORE_DEGREE                     : FontUnit = fontunit!(277);
pub static RADICAL_RULE_THICKNESS                         : FontUnit = fontunit!(66);
pub static RADICAL_VERTICAL_GAP                           : FontUnit = fontunit!(82);
pub static SCRIPT_PERCENT_SCALE_DOWN                      : FontUnit = fontunit_raw!(0xAE); // 68 %
pub static SCRIPT_SCRIPT_PERCENT_SCALE_DOWN               : FontUnit = fontunit_raw!(0x80); // 50 %
pub static SKEWED_FRACTION_HORIZONTAL_GAP                 : FontUnit = fontunit!(300);
pub static SKEWED_FRACTION_VERTICAL_GAP                   : FontUnit = fontunit!(66);
pub static SPACE_AFTER_SCRIPT                             : FontUnit = fontunit!(41);
pub static STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN          : FontUnit = fontunit!(900);
pub static STACK_BOTTOM_SHIFT_DOWN                        : FontUnit = fontunit!(800);
pub static STACK_DISPLAY_STYLE_GAP_MIN                    : FontUnit = fontunit!(462);
pub static STACK_GAP_MIN                                  : FontUnit = fontunit!(198);
pub static STACK_TOP_DISPLAY_STYLE_SHIFT_UP               : FontUnit = fontunit!(580);
pub static STACK_TOP_SHIFT_UP                             : FontUnit = fontunit!(480);
pub static STRETCH_STACK_BOTTOM_SHIFT_DOWN                : FontUnit = fontunit!(600);
pub static STRETCH_STACK_GAP_ABOVE_MIN                    : FontUnit = fontunit!(150);
pub static STRETCH_STACK_GAP_BELOW_MIN                    : FontUnit = fontunit!(150);
pub static STRETCH_STACK_TOP_SHIFT_UP                     : FontUnit = fontunit!(300);
pub static SUB_SUPERSCRIPT_GAP_MIN                        : FontUnit = fontunit!(264);
pub static SUBSCRIPT_BASELINE_DROP_MIN                    : FontUnit = fontunit!(50);
pub static SUBSCRIPT_SHIFT_DOWN                           : FontUnit = fontunit!(250);
pub static SUBSCRIPT_TOP_MAX                              : FontUnit = fontunit!(400);
pub static SUPERSCRIPT_BASELINE_DROP_MAX                  : FontUnit = fontunit!(375);
pub static SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT          : FontUnit = fontunit!(400);
pub static SUPERSCRIPT_BOTTOM_MIN                         : FontUnit = fontunit!(125);
pub static SUPERSCRIPT_SHIFT_UP                           : FontUnit = fontunit!(400);
pub static SUPERSCRIPT_SHIFT_UP_CRAMPED                   : FontUnit = fontunit!(275);
pub static UNDERBAR_EXTRA_DESCENDER                       : FontUnit = fontunit!(66);
pub static UNDERBAR_RULE_THICKNESS                        : FontUnit = fontunit!(66);
pub static UNDERBAR_VERTICAL_GAP                          : FontUnit = fontunit!(198);
pub static UPPER_LIMIT_BASELINE_RISE_MIN                  : FontUnit = fontunit!(300);
pub static UPPER_LIMIT_GAP_MIN                            : FontUnit = fontunit!(150);
