// DO NOT MODIFY.  This file is automatically generated by ___ in the rex-font folder.
//
// Font File: master/xits.otf
// Font Nmae: b'XITS Math'
use font_types::FontUnit;

pub const UNITS_PER_EM: FontUnit = fontunit!(1000);
pub const MIN_CONNECTOR_OVERLAP: FontUnit = fontunit!(50);
pub const NULL_DELIMITER_SPACE: FontUnit = fontunit!(100);
pub const DELIMITER_SHORT_FALL: FontUnit = fontunit!(100);
pub const DELIMITER_FACTOR: FontUnit = fontunit_raw!(0xE6); // 90.1%
pub const ACCENT_BASE_HEIGHT: FontUnit = fontunit!(450);
pub const AXIS_HEIGHT: FontUnit = fontunit!(250);
pub const DELIMITED_SUB_FORMULA_MIN_HEIGHT: FontUnit = fontunit!(1500);
pub const DISPLAY_OPERATOR_MIN_HEIGHT: FontUnit = fontunit!(1450);
pub const FLATTENED_ACCENT_BASE_HEIGHT: FontUnit = fontunit!(662);
pub const FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(198);
pub const FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN: FontUnit = fontunit!(700);
pub const FRACTION_DENOMINATOR_GAP_MIN: FontUnit = fontunit!(66);
pub const FRACTION_DENOMINATOR_SHIFT_DOWN: FontUnit = fontunit!(480);
pub const FRACTION_NUM_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(198);
pub const FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP: FontUnit = fontunit!(580);
pub const FRACTION_NUMERATOR_GAP_MIN: FontUnit = fontunit!(66);
pub const FRACTION_NUMERATOR_SHIFT_UP: FontUnit = fontunit!(480);
pub const FRACTION_RULE_THICKNESS: FontUnit = fontunit!(66);
pub const LOWER_LIMIT_BASELINE_DROP_MIN: FontUnit = fontunit!(600);
pub const LOWER_LIMIT_GAP_MIN: FontUnit = fontunit!(150);
pub const MATH_LEADING: FontUnit = fontunit!(150);
pub const OVERBAR_EXTRA_ASCENDER: FontUnit = fontunit!(66);
pub const OVERBAR_RULE_THICKNESS: FontUnit = fontunit!(66);
pub const OVERBAR_VERTICAL_GAP: FontUnit = fontunit!(198);
pub const RADICAL_DEGREE_BOTTOM_RAISE_PERCENT: FontUnit = fontunit!(70);
pub const RADICAL_DISPLAY_STYLE_VERTICAL_GAP: FontUnit = fontunit!(186);
pub const RADICAL_EXTRA_ASCENDER: FontUnit = fontunit!(66);
pub const RADICAL_KERN_AFTER_DEGREE: FontUnit = fontunit!(-550);
pub const RADICAL_KERN_BEFORE_DEGREE: FontUnit = fontunit!(277);
pub const RADICAL_RULE_THICKNESS: FontUnit = fontunit!(66);
pub const RADICAL_VERTICAL_GAP: FontUnit = fontunit!(82);
pub const SCRIPT_PERCENT_SCALE_DOWN: FontUnit = fontunit_raw!(0xAE); // 68 %
pub const SCRIPT_SCRIPT_PERCENT_SCALE_DOWN: FontUnit = fontunit_raw!(0x80); // 50 %
pub const SKEWED_FRACTION_HORIZONTAL_GAP: FontUnit = fontunit!(300);
pub const SKEWED_FRACTION_VERTICAL_GAP: FontUnit = fontunit!(66);
pub const SPACE_AFTER_SCRIPT: FontUnit = fontunit!(41);
pub const STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN: FontUnit = fontunit!(900);
pub const STACK_BOTTOM_SHIFT_DOWN: FontUnit = fontunit!(800);
pub const STACK_DISPLAY_STYLE_GAP_MIN: FontUnit = fontunit!(462);
pub const STACK_GAP_MIN: FontUnit = fontunit!(198);
pub const STACK_TOP_DISPLAY_STYLE_SHIFT_UP: FontUnit = fontunit!(580);
pub const STACK_TOP_SHIFT_UP: FontUnit = fontunit!(480);
pub const STRETCH_STACK_BOTTOM_SHIFT_DOWN: FontUnit = fontunit!(600);
pub const STRETCH_STACK_GAP_ABOVE_MIN: FontUnit = fontunit!(150);
pub const STRETCH_STACK_GAP_BELOW_MIN: FontUnit = fontunit!(150);
pub const STRETCH_STACK_TOP_SHIFT_UP: FontUnit = fontunit!(300);
pub const SUB_SUPERSCRIPT_GAP_MIN: FontUnit = fontunit!(264);
pub const SUBSCRIPT_BASELINE_DROP_MIN: FontUnit = fontunit!(50);
pub const SUBSCRIPT_SHIFT_DOWN: FontUnit = fontunit!(250);
pub const SUBSCRIPT_TOP_MAX: FontUnit = fontunit!(400);
pub const SUPERSCRIPT_BASELINE_DROP_MAX: FontUnit = fontunit!(375);
pub const SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT: FontUnit = fontunit!(400);
pub const SUPERSCRIPT_BOTTOM_MIN: FontUnit = fontunit!(125);
pub const SUPERSCRIPT_SHIFT_UP: FontUnit = fontunit!(400);
pub const SUPERSCRIPT_SHIFT_UP_CRAMPED: FontUnit = fontunit!(275);
pub const UNDERBAR_EXTRA_DESCENDER: FontUnit = fontunit!(66);
pub const UNDERBAR_RULE_THICKNESS: FontUnit = fontunit!(66);
pub const UNDERBAR_VERTICAL_GAP: FontUnit = fontunit!(198);
pub const UPPER_LIMIT_BASELINE_RISE_MIN: FontUnit = fontunit!(300);
pub const UPPER_LIMIT_GAP_MIN: FontUnit = fontunit!(150);